var mainDiv=document.getElementById("maindiv"),startdiv=document.getElementById("startdiv"),scorediv=document.getElementById("scorediv"),scorelabel=document.getElementById("label"),suspenddiv=document.getElementById("suspenddiv"),enddiv=document.getElementById("enddiv"),planscore=document.getElementById("planscore"),scores=0,kill=document.getElementById("sound-kill"),gameover=document.getElementById("sound-gameover"),first=1,sUserAgent=navigator.userAgent.toLowerCase(),bIsIpad="ipad"==sUserAgent.match(/ipad/i),
bIsIphoneOs="iphone os"==sUserAgent.match(/iphone os/i),bIsMidp="midp"==sUserAgent.match(/midp/i),bIsUc7="rv:1.2.3.4"==sUserAgent.match(/rv:1.2.3.4/i),bIsUc="ucweb"==sUserAgent.match(/ucweb/i),bIsAndroid="android"==sUserAgent.match(/android/i),bIsCE="windows ce"==sUserAgent.match(/windows ce/i),bIsWM="windows mobile"==sUserAgent.match(/windows mobile/i);bIsIpad||bIsIphoneOs||bIsMidp||bIsUc7||bIsUc||bIsAndroid||bIsCE||bIsWM||alert("\u68c0\u6d4b\u5230\u4e3aPC\u6d4f\u89c8\n\u6253\u5f00\u5f71\u54cd\u5f0f\u8bbe\u8ba1\u6a21\u5f0f\uff08Ctrl+Shift+M \uff09\u6b63\u5e38\u6d4f\u89c8\uff08\u6700\u597d\u9009iphone X/XS\uff09");
function plan(b,a,d,c,e,f,g,h,k,l){this.planX=a;this.planY=d;this.imagenode=null;this.planhp=b;this.planscore=f;this.plansizeX=c;this.plansizeY=e;this.planboomimage=k;this.planisdie=!1;this.plandietimes=0;this.plandietime=g;this.plansudu=h;this.planmove=function(){this.imagenode.style.top=5E4>=scores?this.imagenode.offsetTop+this.plansudu+"px":5E4<scores&&1E5>=scores?this.imagenode.offsetTop+this.plansudu+1+"px":1E5<scores&&15E4>=scores?this.imagenode.offsetTop+this.plansudu+2+"px":15E4<scores&&2E5>=
scores?this.imagenode.offsetTop+this.plansudu+3+"px":2E5<scores&&3E5>=scores?this.imagenode.offsetTop+this.plansudu+4+"px":this.imagenode.offsetTop+this.plansudu+5+"px"};this.init=function(){this.imagenode=document.createElement("img");this.imagenode.style.left=this.planX+"px";this.imagenode.style.top=this.planY+"px";this.imagenode.src=l;mainDiv.appendChild(this.imagenode)};this.init()}
function bullet(b,a,d,c,e){this.bulletX=b;this.bulletY=a;this.bulletimage=null;this.bulletattach=1;this.bulletsizeX=d;this.bulletsizeY=c;this.bulletmove=function(){this.bulletimage.style.top=this.bulletimage.offsetTop-20+"px"};this.init=function(){this.bulletimage=document.createElement("img");this.bulletimage.style.left=this.bulletX+"px";this.bulletimage.style.top=this.bulletY+"px";this.bulletimage.src=e;mainDiv.appendChild(this.bulletimage)};this.init()}
function oddbullet(b,a){bullet.call(this,b,a,6,14,"image/bullet1.png")}function enemy(b,a,d,c,e,f,g,h,k,l){plan.call(this,b,random(a,d),-100,c,e,f,g,h,k,l)}function random(b,a){return Math.floor(b+Math.random()*(a-b))}function ourplan(b,a){plan.call(this,1,b,a,66,80,0,660,0,"image/\u672c\u65b9\u98de\u673a\u7206\u70b8.gif","image/\u6211\u7684\u98de\u673a.gif");this.imagenode.setAttribute("id","ourplan")}var dW=$("body").width(),dH=$("body").height();
(function(){function b(){dH=$("body").height();dW=$("body").width();setTimeout(b,1E3)}b()})();function getc(){for(var b=decodeURIComponent(document.cookie).split(";"),a=0;a<b.length;a++){for(var d=b[a];" "==d.charAt(0);)d=d.substring(1);if(0==d.indexOf("score="))return Base64.decode(d.substring(6,d.length))-1+1}return 0}function setc(b){var a=new Date;a.setTime(a.getTime()+31536E6);document.cookie="score="+Base64.encode(b+"")+";expires="+a.toUTCString()+";"}
var selfplan=new ourplan(120,458),ourPlan=document.getElementById("ourplan"),yidong=function(){ourPlan.addEventListener("touchstart",function(b){this.addEventListener("touchmove",function(a){a.preventDefault();a=a.touches[0];ourPlan.style.top=a.pageY-41+"px";ourPlan.style.left=a.pageX-33+"px"},!1);this.addEventListener("touchend",function(a){this.ontouchend=this.ontouchmove=null;var b=b>dW-66?dW-66:b;var c=c>dH-82?dH-82:c;ourPlan.style.left=b+"px";ourPlan.style.top=c+"px"},!1)},!1)},number=0,zanting=
function(){0==number?(suspenddiv.style.display="block",document.removeEventListener?(mainDiv.removeEventListener("touchstart",yidong,!0),bodyobj.removeEventListener("touchstart",bianjie,!0)):document.detachEvent&&(mainDiv.detachEvent("ontouchstart",yidong),bodyobj.detachEvent("ontouchstart",bianjie)),clearInterval(set),number=1):(suspenddiv.style.display="none",document.addEventListener?(mainDiv.addEventListener("touchstart",yidong,!0),bodyobj.addEventListener("touchstart",bianjie,!0)):document.attachEvent&&
(mainDiv.attachEvent("ontouchstart",yidong),bodyobj.attachEvent("ontouchstart",bianjie)),set=setInterval(start,20),number=0)},bianjie=function(b){var a=window.event||b;b=a.clientX;a=a.clientY;0>b||b>dW||0>a||a>dH?document.removeEventListener?mainDiv.removeEventListener("touchstart",yidong,!0):document.detachEvent&&mainDiv.detachEvent("ontouchstart",yidong):document.addEventListener?mainDiv.addEventListener("touchstart",yidong,!0):document.attachEvent&&mainDiv.attachEvent("notouchstart",yidong)},bodyobj=
document.getElementsByTagName("body")[0];
document.addEventListener?(mainDiv.addEventListener("click",yidong,!0),selfplan.imagenode.addEventListener("click",zanting,!0),bodyobj.addEventListener("touchstart",bianjie,!0),suspenddiv.getElementsByTagName("button")[0].addEventListener("click",zanting,!0),suspenddiv.getElementsByTagName("button")[2].addEventListener("click",jixu,!0)):document.attachEvent&&(mainDiv.attachEvent("ontouchstart",yidong),selfplan.imagenode.attachEvent("onclick",zanting),bodyobj.attachEvent("onclick",bianjie),suspenddiv.getElementsByTagName("button")[0].attachEvent("onclick",
zanting),suspenddiv.getElementsByTagName("button")[2].attachEvent("click",jixu,!0));selfplan.imagenode.style.display="none";var enemys=[],bullets=[],mark=0,mark1=0,backgroundPositionY=0;
function start(){568==backgroundPositionY&&(backgroundPositionY=0);mark++;20==mark&&(mark1++,0==mark1%5&&enemys.push(new enemy(6,25,window.innerWidth-25,46,60,5E3,360,random(1,3),"image/\u4e2d\u98de\u673a\u7206\u70b8.gif","image/enemy3_fly_1.png")),20==mark1?(enemys.push(new enemy(12,57,window.innerWidth-57,110,164,3E4,540,1,"image/\u5927\u98de\u673a\u7206\u70b8.gif","image/enemy2_fly_1.png")),mark1=0):enemys.push(new enemy(1,19,window.innerWidth-19,34,24,1E3,360,random(1,4),"image/\u5c0f\u98de\u673a\u7206\u70b8.gif",
"image/enemy1_fly_1.png")),mark=0);for(var b=enemys.length,a=0;a<b;a++)1!=enemys[a].planisdie&&enemys[a].planmove(),enemys[a].imagenode.offsetTop>dH&&(mainDiv.removeChild(enemys[a].imagenode),enemys.splice(a,1),b--),1==enemys[a].planisdie&&(enemys[a].plandietimes+=20,enemys[a].plandietimes==enemys[a].plandietime&&(mainDiv.removeChild(enemys[a].imagenode),enemys.splice(a,1),b--));0==mark%5&&bullets.push(new oddbullet(parseInt(selfplan.imagenode.style.left)+31,parseInt(selfplan.imagenode.style.top)-
10));var d=bullets.length;for(a=0;a<d;a++)bullets[a].bulletmove(),0>bullets[a].bulletimage.offsetTop&&(mainDiv.removeChild(bullets[a].bulletimage),bullets.splice(a,1),d--);for(a=0;a<d;a++)for(var c=0;c<b;c++)if(0==enemys[c].planisdie){if(enemys[c].imagenode.offsetLeft+enemys[c].plansizeX>=selfplan.imagenode.offsetLeft&&enemys[c].imagenode.offsetLeft<=selfplan.imagenode.offsetLeft+selfplan.plansizeX&&enemys[c].imagenode.offsetTop+enemys[c].plansizeY>=selfplan.imagenode.offsetTop+40&&enemys[c].imagenode.offsetTop<=
selfplan.imagenode.offsetTop-20+selfplan.plansizeY&&first){selfplan.imagenode.src="image/\u672c\u65b9\u98de\u673a\u7206\u70b8.gif";this.gameover.play();enddiv.style.display="block";var e=getc(),f=0;scores>e&&(e=scores,f=1);setc(e);planscore.innerHTML=scores;planscore.innerHTML=0<e&&0==f?planscore.innerHTML+"<br/>\u5386\u53f2\u6700\u9ad8\u5206\u4e3a"+e:planscore.innerHTML+"<br/>\u65b0\u7eaa\u5f55\uff01";document.removeEventListener?(mainDiv.removeEventListener("touchstart",yidong,!0),bodyobj.removeEventListener("touchstart",
bianjie,!0)):document.detachEvent&&(mainDiv.detachEvent("ontouchstart",yidong),bodyobj.removeEventListener("touchstart",bianjie,!0));clearInterval(set);first=0}if(bullets[a].bulletimage.offsetLeft+bullets[a].bulletsizeX>enemys[c].imagenode.offsetLeft&&bullets[a].bulletimage.offsetLeft<enemys[c].imagenode.offsetLeft+enemys[c].plansizeX&&bullets[a].bulletimage.offsetTop<=enemys[c].imagenode.offsetTop+enemys[c].plansizeY&&bullets[a].bulletimage.offsetTop+bullets[a].bulletsizeY>=enemys[c].imagenode.offsetTop){enemys[c].planhp-=
bullets[a].bulletattach;0==enemys[c].planhp&&(this.kill.play(),scores+=enemys[c].planscore,scorelabel.innerHTML=scores,enemys[c].imagenode.src=enemys[c].planboomimage,enemys[c].planisdie=!0);mainDiv.removeChild(bullets[a].bulletimage);bullets.splice(a,1);d--;break}}}var set;function begin(){startdiv.style.display="none";mainDiv.style.display="block";selfplan.imagenode.style.display="block";scorediv.style.display="block";set=setInterval(start,20)}function jixu(){location.reload(!0)};
